### ISSUE TITLE
Types are conflicting because of nx-python package node_modules

### ISSUE THREAD

**Issue by sumitparakh** [codeonrocks/nx-python#7]
* **I'm submitting a ...**
  - [x] bug report
  - [ ] feature request
  - [ ] support request 

* **Do you want to request a *feature* or report a *bug*?**
*bug*

* **What is the current behavior?**
dependency inside packages/nx-python is conflicting with the parent level dependency..

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** via
https://plnkr.co or similar (you can use this template as a starting point: http://plnkr.co/edit/tpl:AvJOMERrnz94ekVua0u5).

1. Take clone of the repo
2. Run `yarn install`
3. Now build the project: `yarn nx build nx-python`

3rd step will throw typescript compilation error

* **What is the expected behavior?**
1. I observed that node_modules is added in git under packages/nx-python.. Ideally, node_modules should be git ignored.
2. node_modules under packages/nx-python have almost same no. of dependencies as that of parent node_modules folder and that's why typescript is giving conflicting errors..   Need to fix dependencies in packages/nx-python.

* **What is the motivation / use case for changing the behavior?**
1. Provide error-free and seamless build of nx-python

* **Please tell us about your environment:**
  
Window 10 Pro

* **Other information** (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

![image](https://user-images.githubusercontent.com/4236211/100113912-db0d8300-2e96-11eb-8e04-5439321e1920.png)

Blocks #6

**Comment by sumitparakh** [comment]
Hi @alphacentauri82 , any specific reason for adding node_modules to git?

**Comment by alphacentauri82** [comment]
@sumitparakh that was a mistake on my side, didn't add them to gitignore. Feel free to fix it!

**Comment by sumitparakh** [comment]
> @sumitparakh that was a mistake on my side, didn't add them to gitignore. Feel free to fix it!

Fixed.
